#ifndef OWD_VERSION_H_
#define OWD_VERSION_H_

#define APPLICATION_NAME "Open Weather Data"
#define APPLICATION_CODENAME "owd"
#define APPLICATION_BUILD_DATE "09/08/2018"
#define APPLICATION_BUILD_USER "dshil"
#define APPLICATION_BUILD_HOST "localhost.localdomain"
#define APPLICATION_VERSION_MAJOR 0
#define APPLICATION_VERSION_MINOR 1
#define APPLICATION_VERSION_STRING "0.1"

#endif // OWD_VERSION_H_
